// src/components/HashEncoder.vue
<template>
  <div class="flex flex-col gap-8 justify-start items-center pt-[10vh] min-h-full relative w-full max-w-[800px] mx-auto max-md:gap-6 max-md:pt-[5vh] max-md:px-4">
    <div class="w-full flex flex-col gap-6">
      <div class="flex flex-col gap-2">
        <label for="input-text" class="font-semibold text-(--color-text-secondary) text-sm">输入文本</label>
        <textarea
          id="input-text"
          v-model="inputText"
          @input="autoResize"
          @keydown.ctrl.enter="calculateHash"
          @keydown.meta.enter="calculateHash"
          placeholder="请输入要计算Hash的文本..."
          class="w-full p-3 border-[1.5px] border-(--color-border-default) rounded-lg bg-(--color-input-bg) text-(--color-text-primary) font-mono text-[13px] leading-relaxed resize-none overflow-y-hidden transition-all duration-200 min-h-[120px] focus:outline-none focus:border-(--color-brand) focus:shadow-[0_0_0_2px_var(--color-brand-light)] max-md:min-h-[100px]"
          ref="inputArea"
        ></textarea>
      </div>

      <div class="flex flex-col gap-2">
        <label for="hash-type" class="font-semibold text-(--color-text-secondary) text-sm">选择Hash算法：</label>
        <select
          id="hash-type"
          v-model="selectedHashType"
          class="appearance-none bg-[url('data:image/svg+xml,%3Csvg_xmlns=%27http://www.w3.org/2000/svg%27_width=%2714%27_height=%2714%27_viewBox=%270_0_24_24%27_fill=%27none%27_stroke=%27%23495057%27_stroke-width=%272%27_stroke-linecap=%27round%27_stroke-linejoin=%27round%27%3E%3Cpolyline_points=%276_9_12_15_18_9%27%3E%3C/polyline%3E%3C/svg%3E')] bg-no-repeat bg-[right_12px_center] bg-[length:14px] cursor-pointer transition-all duration-300 border-[1.5px] border-(--color-border-default) rounded-lg py-2.5 pr-9 pl-3 text-sm font-medium text-(--color-text-primary) bg-(--color-input-bg) shadow-[0_1px_3px_var(--color-shadow)] min-w-[180px] hover:border-(--color-brand) hover:shadow-[0_2px_8px_var(--color-brand-light)] hover:-translate-y-[0.5px] focus:outline-none focus:border-(--color-brand) focus:shadow-[0_0_0_2px_var(--color-brand-light),0_2px_8px_var(--color-brand-light)] focus:-translate-y-[0.5px]"
        >
          <option value="md5">MD5</option>
          <option value="sha1">SHA-1</option>
          <option value="sha256">SHA-256</option>
          <option value="sha512">SHA-512</option>
        </select>
      </div>

      <div class="flex gap-3 flex-wrap max-md:flex-col">
        <button @click="calculateHash" class="px-5 py-2.5 border-none rounded-lg text-sm font-medium cursor-pointer transition-all duration-300 min-w-[100px] bg-(--color-brand) text-white hover:bg-(--color-brand-hover) hover:-translate-y-px max-md:w-full">
          计算Hash
        </button>
        <button @click="clearAll" class="px-5 py-2.5 border-none rounded-lg text-sm font-medium cursor-pointer transition-all duration-300 min-w-[100px] bg-(--color-text-tertiary) text-white hover:bg-(--color-text-secondary) hover:-translate-y-px max-md:w-full">
          清空
        </button>
      </div>
    </div>

    <div v-if="hashResult" class="w-full flex flex-col gap-6">
      <div class="flex flex-col gap-2">
        <label class="font-semibold text-(--color-text-secondary) text-sm">Hash结果：</label>
        <div class="bg-(--color-bg-secondary) p-4 rounded-lg border border-(--color-border-default)">
          <div class="font-mono text-sm break-all text-(--color-text-primary) leading-relaxed">{{ hashResult }}</div>
        </div>
        <button @click="copyResult" class="px-5 py-2.5 border-none rounded-lg text-sm font-medium cursor-pointer transition-all duration-300 min-w-[100px] bg-(--color-success) text-white hover:bg-(--color-success-hover) hover:-translate-y-px">
          复制结果
        </button>
      </div>
    </div>

    <div v-if="message" :class="['fixed top-5 right-5 z-[1000] max-w-[300px] p-3 px-4 rounded-lg text-sm font-medium shadow-[0_4px_12px_rgba(0,0,0,0.15)] animate-slide-in border max-md:right-2.5 max-md:left-2.5 max-md:max-w-none', messageType === 'success' ? 'bg-(--color-success-bg) text-(--color-success-text) border-(--color-success-border)' : 'bg-(--color-error-bg) text-(--color-error-text) border-(--color-error-border)']">
      {{ message }}
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref, watch } from 'vue'
import CryptoJS from 'crypto-js'

type MessageType = 'success' | 'error'
type HashType = 'md5' | 'sha1' | 'sha256' | 'sha512'

const inputText = ref<string>('')
const hashResult = ref<string>('')
const selectedHashType = ref<HashType>('md5')
const message = ref<string>('')
const messageType = ref<MessageType>('success')
const inputArea = ref<HTMLTextAreaElement | null>(null)

const calculateHash = async (): Promise<void> => {
  if (!inputText.value.trim()) {
    hashResult.value = ''
    return
  }

  try {
    const text = inputText.value.trim()
    let result = ''

    switch (selectedHashType.value) {
      case 'md5':
        result = CryptoJS.MD5(text).toString()
        break
      case 'sha1':
        result = CryptoJS.SHA1(text).toString()
        break
      case 'sha256':
        result = CryptoJS.SHA256(text).toString()
        break
      case 'sha512':
        result = CryptoJS.SHA512(text).toString()
        break
      default:
        throw new Error('不支持的哈希算法')
    }

    hashResult.value = result
  } catch (error) {
    const errorMessage = error instanceof Error ? error.message : String(error)
    showMessage('Hash计算失败：' + errorMessage, 'error')
  }
}

const copyResult = async (): Promise<void> => {
  if (!hashResult.value) return

  try {
    await navigator.clipboard.writeText(hashResult.value)
    showMessage('Hash值已复制到剪贴板！', 'success')
  } catch (error) {
    const textArea = document.createElement('textarea')
    textArea.value = hashResult.value
    document.body.appendChild(textArea)
    textArea.select()
    document.execCommand('copy')
    document.body.removeChild(textArea)
    showMessage('Hash值已复制到剪贴板！', 'success')
  }
}

const clearAll = (): void => {
  inputText.value = ''
  hashResult.value = ''
  message.value = ''
  autoResize()
}

const showMessage = (text: string, type: MessageType): void => {
  message.value = text
  messageType.value = type
  setTimeout(() => {
    message.value = ''
  }, 3000)
}

const autoResize = (): void => {
  const area = inputArea.value
  if (area && area instanceof HTMLTextAreaElement) {
    area.style.height = 'auto'
    area.style.height = area.scrollHeight + 'px'
  }
}

watch(inputText, (newVal: string) => {
  if (newVal.trim()) {
    calculateHash()
  } else {
    hashResult.value = ''
  }
})

watch(selectedHashType, () => {
  if (inputText.value.trim()) {
    calculateHash()
  }
})
</script>

// src/pages/HashEncoder.tsx
import { useState, useRef, useEffect } from 'react'
import CryptoJS from 'crypto-js'
import { useAutoResize } from '../hooks/useAutoResize'
import { useMessage } from '../hooks/useMessage'
import { useClipboard } from '../hooks/useClipboard'
import type { HashType } from '../types'
import Toast from '../components/Toast'

export default function HashEncoder() {
  const [inputText, setInputText] = useState('')
  const [hashResult, setHashResult] = useState('')
  const [selectedHashType, setSelectedHashType] = useState<HashType>('md5')
  const { message, messageType, showMessage } = useMessage()
  const { copy } = useClipboard()
  const inputRef = useRef<HTMLTextAreaElement>(null)
  useAutoResize(inputRef, inputText)

  const calculateHash = (text: string, type: HashType) => {
    if (!text.trim()) {
      setHashResult('')
      return
    }
    try {
      const trimmed = text.trim()
      let result = ''
      switch (type) {
        case 'md5': result = CryptoJS.MD5(trimmed).toString(); break
        case 'sha1': result = CryptoJS.SHA1(trimmed).toString(); break
        case 'sha256': result = CryptoJS.SHA256(trimmed).toString(); break
        case 'sha512': result = CryptoJS.SHA512(trimmed).toString(); break
      }
      setHashResult(result)
    } catch (error) {
      showMessage('Hash计算失败：' + (error instanceof Error ? error.message : String(error)), 'error')
    }
  }

  useEffect(() => {
    calculateHash(inputText, selectedHashType)
  }, [inputText, selectedHashType])

  const handleCopy = async () => {
    if (!hashResult) return
    const ok = await copy(hashResult)
    if (ok) showMessage('Hash值已复制到剪贴板！', 'success')
  }

  const handleClear = () => {
    setInputText('')
    setHashResult('')
  }

  const handleKeyDown = (e: React.KeyboardEvent) => {
    if ((e.ctrlKey || e.metaKey) && e.key === 'Enter') calculateHash(inputText, selectedHashType)
  }

  return (
    <div className="flex flex-col gap-8 items-center pt-[10vh] min-h-full w-full max-w-[800px] mx-auto max-md:gap-6 max-md:pt-[5vh] max-md:px-4">
      <div className="w-full flex flex-col gap-6">
        <div>
          <label htmlFor="input-text" className="block mb-2 font-semibold text-gray-600 dark:text-gray-300 text-sm">
            输入文本
          </label>
          <textarea
            id="input-text"
            ref={inputRef}
            value={inputText}
            onChange={e => setInputText(e.target.value)}
            onKeyDown={handleKeyDown}
            placeholder="请输入要计算Hash的文本..."
            className="w-full px-3 py-3 border-[1.5px] border-gray-300 dark:border-neutral-600 rounded-lg text-[13px] font-mono bg-white dark:bg-neutral-800 text-gray-900 dark:text-gray-100 min-h-[120px] resize-none overflow-y-hidden leading-relaxed transition-all duration-200 focus:outline-none focus:border-primary focus:ring-2 focus:ring-primary-light max-md:min-h-[100px]"
          />
        </div>

        <div>
          <label htmlFor="hash-type" className="block mb-2 font-semibold text-gray-600 dark:text-gray-300 text-sm">
            选择Hash算法：
          </label>
          <select
            id="hash-type"
            value={selectedHashType}
            onChange={e => setSelectedHashType(e.target.value as HashType)}
            className="appearance-none cursor-pointer border-[1.5px] border-gray-300 dark:border-neutral-600 rounded-lg px-3 py-2.5 pr-9 text-sm font-medium text-gray-900 dark:text-gray-100 bg-white dark:bg-neutral-800 shadow-sm min-w-[180px] transition-all duration-300 hover:border-primary hover:shadow-md hover:-translate-y-px focus:outline-none focus:border-primary focus:ring-2 focus:ring-primary-light bg-[url('data:image/svg+xml,%3Csvg%20xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%22%20width%3D%2214%22%20height%3D%2214%22%20viewBox%3D%220%200%2024%2024%22%20fill%3D%22none%22%20stroke%3D%22%23495057%22%20stroke-width%3D%222%22%20stroke-linecap%3D%22round%22%20stroke-linejoin%3D%22round%22%3E%3Cpolyline%20points%3D%226%209%2012%2015%2018%209%22%3E%3C%2Fpolyline%3E%3C%2Fsvg%3E')] bg-no-repeat bg-[right_12px_center] bg-[length:14px]"
          >
            <option value="md5">MD5</option>
            <option value="sha1">SHA-1</option>
            <option value="sha256">SHA-256</option>
            <option value="sha512">SHA-512</option>
          </select>
        </div>

        <div className="flex gap-3 flex-wrap max-md:flex-col">
          <button onClick={() => calculateHash(inputText, selectedHashType)} className="px-5 py-2.5 border-none rounded-lg text-sm font-medium cursor-pointer transition-all duration-300 min-w-[100px] bg-primary text-white hover:bg-primary-hover hover:-translate-y-px max-md:w-full">
            计算Hash
          </button>
          <button onClick={handleClear} className="px-5 py-2.5 border-none rounded-lg text-sm font-medium cursor-pointer transition-all duration-300 min-w-[100px] bg-gray-500 dark:bg-gray-600 text-white hover:bg-gray-600 dark:hover:bg-gray-500 hover:-translate-y-px max-md:w-full">
            清空
          </button>
        </div>
      </div>

      {hashResult && (
        <div className="w-full flex flex-col gap-6">
          <div>
            <label className="block mb-2 font-semibold text-gray-600 dark:text-gray-300 text-sm">Hash结果：</label>
            <div className="bg-gray-50 dark:bg-neutral-800 p-4 rounded-lg border border-gray-300 dark:border-neutral-600">
              <div className="font-mono text-sm break-all text-gray-900 dark:text-gray-100 leading-relaxed">{hashResult}</div>
            </div>
            <button onClick={handleCopy} className="mt-2 px-5 py-2.5 border-none rounded-lg text-sm font-medium cursor-pointer transition-all duration-300 bg-success text-white hover:bg-success-hover hover:-translate-y-px">
              复制结果
            </button>
          </div>
        </div>
      )}
      <Toast message={message} type={messageType} />
    </div>
  )
}
