// src/components/tools/JsonFormatter/index.tsx
import { useState, useRef, useEffect, useCallback } from 'react'
import { useToast } from '../../../context/ToastContext'
import JsonTreeNode from './JsonTreeNode'

export default function JsonFormatter() {
  const [text, setText] = useState('')
  const [parsed, setParsed] = useState<unknown>(null)
  const [expandedPaths, setExpandedPaths] = useState<Set<string>>(new Set())
  const textareaRef = useRef<HTMLTextAreaElement>(null)
  const parseTimerRef = useRef<ReturnType<typeof setTimeout>>(undefined)
  const { showToast } = useToast()

  const autoResize = useCallback(() => {
    const el = textareaRef.current
    if (!el) return
    el.style.height = 'auto'
    el.style.height = el.scrollHeight + 'px'
  }, [])

  useEffect(() => { autoResize() }, [text, autoResize])

  const expandAll = useCallback((obj: unknown, prefix = 'root') => {
    const paths = new Set<string>()
    const walk = (o: unknown, p: string) => {
      if (o && typeof o === 'object') {
        paths.add(p)
        Object.keys(o).forEach(k => walk((o as Record<string, unknown>)[k], `${p}.${k}`))
      }
    }
    walk(obj, prefix)
    return paths
  }, [])

  useEffect(() => {
    if (parseTimerRef.current) clearTimeout(parseTimerRef.current)
    if (!text.trim()) { setParsed(null); return }
    parseTimerRef.current = setTimeout(() => {
      try {
        const obj = JSON.parse(text)
        setParsed(obj)
        setExpandedPaths(expandAll(obj))
      } catch {
        setParsed(null)
      }
    }, 500)
    return () => { if (parseTimerRef.current) clearTimeout(parseTimerRef.current) }
  }, [text, expandAll])

  const format = () => {
    if (!text.trim()) return showToast('请输入要格式化的JSON数据', 'error')
    try {
      const obj = JSON.parse(text)
      setText(JSON.stringify(obj, null, 2))
      setParsed(obj)
      setExpandedPaths(expandAll(obj))
      showToast('JSON格式化成功', 'success')
    } catch (e) {
      showToast('JSON格式错误：' + (e instanceof Error ? e.message : String(e)), 'error')
    }
  }

  const compress = () => {
    if (!text.trim()) return showToast('请输入要压缩的JSON数据', 'error')
    try {
      const obj = JSON.parse(text)
      setText(JSON.stringify(obj))
      setParsed(obj)
      setExpandedPaths(expandAll(obj))
      showToast('JSON压缩成功', 'success')
    } catch (e) {
      showToast('JSON格式错误：' + (e instanceof Error ? e.message : String(e)), 'error')
    }
  }

  const togglePath = (path: string) => {
    setExpandedPaths(prev => {
      const next = new Set(prev)
      if (next.has(path)) next.delete(path)
      else next.add(path)
      return next
    })
  }

  const handleKeyDown = (e: React.KeyboardEvent) => {
    if ((e.ctrlKey || e.metaKey) && e.key === 'Enter') format()
  }

  return (
    <div className="flex flex-col gap-4">
      <label className="text-sm font-semibold text-slate-600 dark:text-slate-400">输入JSON</label>
      <textarea
        ref={textareaRef}
        value={text}
        onChange={e => setText(e.target.value)}
        onKeyDown={handleKeyDown}
        placeholder="请输入要格式化的JSON数据..."
        className="w-full min-h-[120px] px-4 py-3 rounded-lg border border-slate-200 dark:border-slate-700 bg-white dark:bg-slate-800 text-slate-900 dark:text-slate-100 font-mono text-sm resize-none overflow-hidden focus:outline-none focus:ring-2 focus:ring-indigo-500 transition-shadow"
      />
      <div className="flex gap-2 flex-wrap">
        <button onClick={format} className="flex-1 min-w-[100px] px-4 py-2.5 rounded-lg bg-indigo-600 text-white text-sm font-medium hover:bg-indigo-700 transition-colors">格式化</button>
        <button onClick={compress} className="flex-1 min-w-[100px] px-4 py-2.5 rounded-lg border border-indigo-600 text-indigo-600 dark:border-indigo-400 dark:text-indigo-400 text-sm font-medium hover:bg-indigo-50 dark:hover:bg-indigo-950 transition-colors">压缩</button>
        <button onClick={() => { setText(''); setParsed(null); setExpandedPaths(new Set()) }} className="flex-1 min-w-[100px] px-4 py-2.5 rounded-lg bg-red-500 text-white text-sm font-medium hover:bg-red-600 transition-colors">清空</button>
      </div>
      {parsed !== null && (
        <div className="p-4 rounded-lg bg-slate-100 dark:bg-slate-800 border border-slate-200 dark:border-slate-700 font-mono text-sm overflow-auto max-h-[600px]">
          <JsonTreeNode data={parsed} keyName="root" level={0} expandedPaths={expandedPaths} onToggle={togglePath} />
        </div>
      )}
    </div>
  )
}

// src/components/JsonFormatter.vue
<template>
  <div class="flex flex-col gap-8 justify-start items-center pt-[10vh] min-h-full relative max-md:gap-6 max-md:pt-[5vh]">
    <div class="flex flex-col gap-6 w-full max-w-[800px]">
      <div class="mb-0">
        <label for="json-input" class="block mb-2 font-semibold text-(--color-text-secondary) text-sm">输入JSON</label>
        <textarea
          id="json-input"
          v-model="inputText"
          placeholder="请输入要格式化的JSON数据..."
          @keydown.ctrl.enter="formatJson"
          @keydown.meta.enter="formatJson"
          class="w-full px-[18px] py-4 border border-(--color-border-default) rounded-lg text-[15px] transition-all duration-200 font-mono bg-(--color-input-bg) text-(--color-text-primary) min-h-[120px] text-[13px] leading-relaxed resize-none overflow-y-hidden focus:outline-none focus:border-(--color-brand) focus:shadow-[0_0_0_3px_var(--color-brand-light)] max-md:min-h-[100px]"
          ref="inputArea"
          @input="autoResize()"
        ></textarea>
      </div>

      <div class="flex gap-3 flex-wrap max-md:flex-col">
        <button @click="formatJson" class="px-6 py-3 border-none rounded-lg text-[15px] font-medium cursor-pointer transition-all duration-200 flex-1 min-w-[110px] inline-flex items-center justify-center gap-2 bg-(--color-brand) text-white hover:bg-(--color-brand-hover) hover:-translate-y-px hover:shadow-[0_4px_12px_var(--color-shadow)] disabled:opacity-60 disabled:cursor-not-allowed max-md:flex-none">
          <span>格式化</span>
        </button>
        <button @click="compressJson" class="px-6 py-3 border border-(--color-brand) rounded-lg text-[15px] font-medium cursor-pointer transition-all duration-200 flex-1 min-w-[110px] inline-flex items-center justify-center gap-2 bg-(--color-bg-primary) text-(--color-brand) hover:bg-(--color-bg-hover) hover:-translate-y-px disabled:opacity-60 disabled:cursor-not-allowed max-md:flex-none">
          <span>压缩</span>
        </button>
        <button @click="clearAll" class="px-6 py-3 border-none rounded-lg text-[15px] font-medium cursor-pointer transition-all duration-200 flex-1 min-w-[110px] inline-flex items-center justify-center gap-2 bg-(--color-danger) text-white hover:bg-(--color-danger-hover) hover:-translate-y-px disabled:opacity-60 disabled:cursor-not-allowed max-md:flex-none">
          <span>清空</span>
        </button>
      </div>

      <!-- JSON树视图 -->
      <div v-if="parsedJson !== null" class="w-full mt-6">
        <div class="bg-(--color-bg-secondary) border border-(--color-border-default) rounded-lg p-4 font-mono text-[13px] leading-relaxed overflow-x-auto max-h-[600px] overflow-y-auto max-md:max-h-[400px]">
          <JsonTreeNode
            :data="parsedJson"
            :keyName="'root'"
            :level="0"
            :expandedPaths="expandedPaths"
            @toggle="togglePath"
          />
        </div>
      </div>
    </div>

    <div v-if="message" :class="['fixed top-5 right-5 z-[1000] max-w-[300px] p-3 px-4 rounded-lg text-sm border animate-slide-in max-md:right-2.5 max-md:left-2.5 max-md:max-w-none', messageType === 'success' ? 'bg-(--color-success-bg) text-(--color-success-text) border-(--color-success-border)' : 'bg-(--color-error-bg) text-(--color-error-text) border-(--color-error-border)']">
      {{ message }}
    </div>
  </div>
</template>

<script setup>
import { ref, watch, onMounted, onBeforeUnmount, nextTick } from 'vue'
import JsonTreeNode from './JsonTreeNode.vue'

const inputText = ref('')
const message = ref('')
const messageType = ref('success')
const parsedJson = ref(null)
const expandedPaths = ref(new Set())
const parseTimeout = ref(null)
const inputArea = ref(null)

const autoParseJson = () => {
  // 清除之前的定时器
  if (parseTimeout.value) {
    clearTimeout(parseTimeout.value)
  }

  // 如果输入为空，清空树视图
  if (!inputText.value.trim()) {
    parsedJson.value = null
    return
  }

  // 使用防抖，500ms后自动解析
  parseTimeout.value = setTimeout(() => {
    try {
      const parsed = JSON.parse(inputText.value)
      parsedJson.value = parsed
      expandedPaths.value.clear()
      expandAll()
    } catch (error) {
      // 静默处理错误，只在格式化/压缩时显示错误消息
      parsedJson.value = null
    }
  }, 500)
}

const formatJson = () => {
  if (!inputText.value.trim()) {
    showMessage('请输入要格式化的JSON数据', 'error')
    return
  }

  try {
    // 先解析JSON确保格式正确
    const parsed = JSON.parse(inputText.value)
    // 格式化输出，使用2个空格缩进，直接覆盖输入框
    inputText.value = JSON.stringify(parsed, null, 2)
    parsedJson.value = parsed
    expandedPaths.value.clear()
    expandAll()
    showMessage('JSON格式化成功！', 'success')
  } catch (error) {
    parsedJson.value = null
    showMessage('JSON格式错误：' + error.message, 'error')
  }
}

const compressJson = () => {
  if (!inputText.value.trim()) {
    showMessage('请输入要压缩的JSON数据', 'error')
    return
  }

  try {
    // 先解析JSON确保格式正确
    const parsed = JSON.parse(inputText.value)
    // 压缩输出，无缩进，直接覆盖输入框
    inputText.value = JSON.stringify(parsed)
    parsedJson.value = parsed
    expandedPaths.value.clear()
    expandAll()
    showMessage('JSON压缩成功！', 'success')
  } catch (error) {
    parsedJson.value = null
    showMessage('JSON格式错误：' + error.message, 'error')
  }
}

const clearAll = () => {
  inputText.value = ''
  message.value = ''
  parsedJson.value = null
  expandedPaths.value.clear()
  nextTick(() => {
    autoResize()
  })
}

const showMessage = (text, type) => {
  message.value = text
  messageType.value = type
  setTimeout(() => {
    message.value = ''
  }, 3000)
}

const autoResize = () => {
  const area = inputArea.value
  if (area && area instanceof HTMLTextAreaElement) {
    area.style.height = 'auto'
    area.style.height = area.scrollHeight + 'px'
  }
}

const togglePath = (path) => {
  if (expandedPaths.value.has(path)) {
    expandedPaths.value.delete(path)
  } else {
    expandedPaths.value.add(path)
  }
  expandedPaths.value = new Set(expandedPaths.value)
}

const expandAll = () => {
  const collectPaths = (obj, currentPath = '') => {
    if (obj && typeof obj === 'object') {
      expandedPaths.value.add(currentPath)
      Object.keys(obj).forEach(key => {
        const newPath = currentPath ? `${currentPath}.${key}` : key
        collectPaths(obj[key], newPath)
      })
    }
  }
  collectPaths(parsedJson.value, 'root')
  expandedPaths.value = new Set(expandedPaths.value)
}

const collapseAll = () => {
  expandedPaths.value.clear()
  expandedPaths.value = new Set(expandedPaths.value)
}

watch(inputText, () => {
  nextTick(() => autoResize())
  autoParseJson()
})

onMounted(() => {
  autoResize()
})

onBeforeUnmount(() => {
  // 清理定时器
  if (parseTimeout.value) {
    clearTimeout(parseTimeout.value)
  }
})
</script>
